

s_texture[e_texture.count] g_textures;
s_animation_data[e_animation.count] g_animations;
s8[c_max_tiles][c_max_tiles] g_tiles;
s_camera camera;
float delta;
float update_timer;
s_v2 tile_size;
s_v2 player_size;
s_player player;
s_projectiles projectiles;
s_v2 projectile_size;
s_v2 mouse;
s_v2 world_mouse;
s_state game_state;
s_input_data input;
s_editor editor;
int animation_count = 0;
s_animation[128] animations;
